// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxdxhupdrlqohcspdzbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZHhodXBkcmxxb2hjc3BkemJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjAwODksImV4cCI6MjA1OTQzNjA4OX0.bsZX2_Nzwx2ysm6SJxdfgzw-LeojYTYAQ05YFSBrDo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);